services:
  api:
    container_name: api-container
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    image: api-image:latest
    env_file:
      - .env
    networks:
      - db-network
      - cache-network
      - web-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  client:
    container_name: client-container
    image: client-image:latest
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - API_URL=${API_URL}
    volumes:
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/letsencrypt/live/${DOMAIN}/privkey.pem:ro
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN}/fullchain.pem:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web-network
    depends_on:
      - api

  redis:
    container_name: redis-container
    image: redis:latest
    volumes:
      - redis-volume:/data
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - .env
    networks:
      - cache-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mysql:
    container_name: mysql-container
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    networks:
      - db-network
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - "--default-time-zone=Asia/Seoul"
      - "--ft_min_word_len=1"
      - "--innodb_ft_min_token_size=1"
      - "--ngram_token_size=1"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  db-volume:
  redis-volume:

networks:
  db-network:
  cache-network:
  web-network:
