global:
  scrape_interval: 30s
  evaluation_interval: 30s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-container:9090']

  - job_name: 'api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api:9100']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
