services:
  redis:
    container_name: redis-container
    image: redis:latest
    volumes:
      - redis-volume:/data
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file:
      - .env
    networks:
      - cache-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  db-volume:
  redis-volume:
  grafana-data:

networks:
  db-network:
  cache-network:
  web-network:
  monitor-network:
