services:
  #    mysql:
  #      image: mysql:8.0
  #      container_name: testdb
  #      ports:
  #        - "${DATABASE_PORT}:3306"
  #      environment:
  #        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #        MYSQL_DATABASE: ${DATABASE_NAME}
  #        TZ: Asia/Seoul
  #      volumes:
  #        - mysql-volume:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_dev
    volumes:
      - redis-volume:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis-volume:
#  mysql-volume:
